import Footer from '@/components/custom/footer'
import Header from '@/components/custom/header'
import AppProvider from '@/contexts/app'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { Open_Sans } from 'next/font/google'
import './globals.css'

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open_sans',
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  const messages = await getMessages()
  return (
    <html lang={locale} className="h-full">
      <NextIntlClientProvider messages={messages}>
        <AppProvider>
          <body className={`${openSans.className} antialiased h-full flex flex-col`}>
            <Header />
            <main className="flex-1 bg-[grey] mt-[96px]">{children}</main>
            <Footer />
          </body>
        </AppProvider>
      </NextIntlClientProvider>
    </html>
  )
}
